### ISSUE TITLE
Add a button in the tracking list for users to manage their own episodes.

### ISSUE THREAD

**Issue by NeKoOuO** [andannn/aniflow#207]

**Comment by andannn** [comment]
I dont want to add extra button to tracking list.  
Instead, I used a long-press gesture to implement this feature.
Users might have difficult to discover this feature, so I want to add toturial dialog for it #223 .
https://github.com/user-attachments/assets/9e2780b1-5c5c-4456-a81e-7f56a93848b3

**Comment by NeKoOuO** [comment]
Ohh i think it's okay
